
export const beauticians = [
    {
        id: 'beautician2',
        name: 'Emma Thompson',
        image: 'https://randomuser.me/api/portraits/women/1.jpg',
        type: 'Makeup Artist',
        description: 'Emma is a talented makeup artist with several years of experience in the beauty industry. She has worked with various clients, from brides to models, and has an eye for creating stunning makeup looks that enhance natural beauty. Her attention to detail and artistic skills make her a sought-after professional.',
        rating: 4.8,
        services: ['Bridal Makeup', 'Special Occasion Makeup', 'Editorial Makeup'],
    },
    {
        id: 'beautician3',
        name: 'Michael Johnson',
        image: 'https://randomuser.me/api/portraits/men/2.jpg',
        type: 'Nail Technician',
        description: 'Michael is a skilled nail technician known for his creative nail designs and impeccable nail art. He stays up-to-date with the latest nail trends and techniques, ensuring his clients get the best and most fashionable nail treatments. Whether it\'s a classic manicure or intricate nail art, Michael never fails to impress.',
        rating: 4.5,
        services: ['Manicure', 'Pedicure', 'Nail Extensions'],
    },
    {
        id: 'beautician4',
        name: 'Olivia Green',
        image: 'https://randomuser.me/api/portraits/women/3.jpg',
        type: 'Esthetician',
        description: 'Olivia is a certified esthetician dedicated to providing top-notch skincare services. She offers a range of facial treatments tailored to individual skin types and concerns. Her expertise in skincare combined with her gentle approach creates a relaxing and rejuvenating experience for her clients.',
        rating: 4.9,
        services: ['Customized Facials', 'Chemical Peels', 'Microdermabrasion'],
    },
    {
        id: 'beautician5',
        name: 'Daniel Adams',
        image: 'https://randomuser.me/api/portraits/men/4.jpg',
        type: 'Hairstylist',
        description: 'Daniel is a creative and passionate hairstylist who can transform any hair into a work of art. From trendy cuts to vibrant hair colors, Daniel loves experimenting with different styles to suit his clients\' personalities. His dedication to hair care and styling makes him a trusted hairstylist.',
        rating: 4.7,
        services: ['Haircuts', 'Hair Coloring', 'Hair Treatments'],
    },
    {
        id: 'beautician6',
        name: 'Sophia Lee',
        image: 'https://randomuser.me/api/portraits/women/5.jpg',
        type: 'Makeup Artist',
        description: 'Sophia is a highly skilled makeup artist with a keen eye for detail. She is known for her ability to create flawless and natural-looking makeup looks that enhance her clients\' features. Whether it\'s a glamorous evening look or a subtle day look, Sophia always ensures her clients feel confident and beautiful.',
        rating: 4.9,
        services: ['Wedding Makeup', 'Event Makeup', 'Photography Makeup'],
    },
    {
        id: 'beautician7',
        name: 'Alexander Clark',
        image: 'https://randomuser.me/api/portraits/men/6.jpg',
        type: 'Barber',
        description: 'Alexander is a talented barber with expertise in various men\'s grooming services. He takes pride in creating clean and precise haircuts and stylish beard designs. His friendly demeanor and attention to detail make every visit to his barbershop a pleasant experience for his clients.',
        rating: 4.6,
        services: ['Men\'s Haircuts', 'Beard Trimming', 'Hot Towel Shaves'],
    },
    {
        id: 'beautician8',
        name: 'Ava Mitchell',
        image: 'https://randomuser.me/api/portraits/women/7.jpg',
        type: 'Manicurist',
        description: 'Ava is a skilled manicurist specializing in nail care and nail art. She has a vast collection of nail polishes and accessories, allowing her to create unique and eye-catching nail designs. Whether it\'s a classic French manicure or intricate nail art, Ava ensures her clients\' nails look stunning.',
        rating: 4.8,
        services: ['Gel Manicures', 'Nail Art', 'Nail Extensions'],
    },
    {
        id: 'beautician9',
        name: 'William Turner',
        image: 'https://randomuser.me/api/portraits/men/8.jpg',
        type: 'Hairstylist',
        description: 'William is a passionate hairstylist with an artistic flair. He loves experimenting with different haircuts and styles to suit his clients\' personalities and preferences. Whether it\'s a sleek bob or a trendy pixie cut, William ensures his clients leave the salon feeling confident and stylish.',
        rating: 4.7,
        services: ['Haircuts', 'Hair Styling', 'Hair Treatments'],
    },
    {
        id: 'beautician10',
        name: 'Isabella Cooper',
        image: 'https://randomuser.me/api/portraits/women/9.jpg',
        type: 'Esthetician',
        description: 'Isabella is a dedicated esthetician focused on providing customized skincare solutions to her clients. She specializes in facials and skin treatments that target specific skin concerns, helping her clients achieve a radiant and healthy complexion. Isabella\'s passion for skincare shines through in every treatment she offers.',
        rating: 4.9,
        services: ['Facials', 'Skin Analysis', 'Acne Treatments'],
    },
    {
        id: 'beautician18',
        name: 'Ava Mitchell',
        image: 'https://randomuser.me/api/portraits/women/7.jpg',
        type: 'Manicurist',
        description: 'Ava is a skilled manicurist specializing in nail care and nail art. She has a vast collection of nail polishes and accessories, allowing her to create unique and eye-catching nail designs. Whether it\'s a classic French manicure or intricate nail art, Ava ensures her clients\' nails look stunning.',
        rating: 4.8,
        services: ['Gel Manicures', 'Nail Art', 'Nail Extensions'],
    },
    {
        id: 'beautician19',
        name: 'William Turner',
        image: 'https://randomuser.me/api/portraits/men/8.jpg',
        type: 'Hairstylist',
        description: 'William is a passionate hairstylist with an artistic flair. He loves experimenting with different haircuts and styles to suit his clients\' personalities and preferences. Whether it\'s a sleek bob or a trendy pixie cut, William ensures his clients leave the salon feeling confident and stylish.',
        rating: 4.7,
        services: ['Haircuts', 'Hair Styling', 'Hair Treatments'],
    },
    {
        id: 'beautician100',
        name: 'Isabella Cooper',
        image: 'https://randomuser.me/api/portraits/women/9.jpg',
        type: 'Esthetician',
        description: 'Isabella is a dedicated esthetician focused on providing customized skincare solutions to her clients. She specializes in facials and skin treatments that target specific skin concerns, helping her clients achieve a radiant and healthy complexion. Isabella\'s passion for skincare shines through in every treatment she offers.',
        rating: 4.9,
        services: ['Facials', 'Skin Analysis', 'Acne Treatments'],
    },
];
